"""Initial migration with User and Product models.

Revision ID: 7f0e03a82e3e
Revises: 
Create Date: 2025-10-21 17:05:14.589140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0e03a82e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_state')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_title', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('p_description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('p_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('p_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('p_special', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('p_special')
        batch_op.drop_column('p_amount')
        batch_op.drop_column('p_price')
        batch_op.drop_column('p_description')
        batch_op.drop_column('p_title')

    op.create_table('website_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
